server:
  port: ${PRODUCER_PORT:8081}

spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

vehicle-listing:
  kafka:
    listing-topic: ${KAFKA_LISTING_TOPIC:vehicle-listing-events}

logging:
  level:
    com.vehiclelisting.producer: INFO
